### PR TITLE
Fix `make test` errors

### LINKED ISSUE #65: A couple of errors when running `make test`.
I'm receiving a couple of errors when running `make test`. 

1.) It appears this one has been broken for some time, which is odd since I'm pretty diligent about running `make test` when doing work locally and reviewing PRs. I have no other explanation other than to say it's been broken for a while.

The problem is that the example JSON string we use to unmarshal into an Annotation type for the purposes of the test incorrectly has a "type" property instead of a "kind" property. This change to the Annotation schema was made in an [early PR](https://github.com/project-alvarium/alvarium-sdk-go/commit/358c41e3ac4de5fa346c79537ca945f9440ca96c) from July 2021.

To fix the test "type" should be changed to "kind" in the sample JSON string and the test hash value aligned with the new value generated by the test.
```
--- FAIL: TestSignAnnotation (0.00s)
    --- FAIL: TestSignAnnotation/valid_ed25519_signature (0.00s)
        base_test.go:95: 
            	Error Trace:	/home/tsconn/Documents/source/github/public/tsconn23/alvarium-sdk-go/internal/annotators/base_test.go:95
            	Error:      	Not equal: 
            	            	expected: "dafcee0a1844b9c5c0db87252067afc06853afefa14b1711a7c24a6eabc6f6b76b91f8aae2ce54f74b54500dbaf303fbb23dc550e151cfe03cef68ae26a22306"
            	            	actual  : "71819f73d6cb76aae901d08281c158ea9ca2912291d326b6c7118c978d28d522fc28ab3a4006df7af8c8ae0ac643573b35f0c3db9a6153d4b110ce325f974c0c"
            	            	
            	            	Diff:
            	            	--- Expected
            	            	+++ Actual
            	            	@@ -1 +1 @@
            	            	-dafcee0a1844b9c5c0db87252067afc06853afefa14b1711a7c24a6eabc6f6b76b91f8aae2ce54f74b54500dbaf303fbb23dc550e151cfe03cef68ae26a22306
            	            	+71819f73d6cb76aae901d08281c158ea9ca2912291d326b6c7118c978d28d522fc28ab3a4006df7af8c8ae0ac643573b35f0c3db9a6153d4b110ce325f974c0c
            	Test:       	TestSignAnnotation/valid_ed25519_signature
FAIL
```

2.) I suspect this one is due to the commented out logic related to the annotator.Kind validation which we have proposed removing in issue #62 
```
--- FAIL: TestSDKInfo_AnnotationInvalid (0.00s)
    functions.go:36: did not receive expected error: test sdk invalid annotation
FAIL
coverage: 42.6% of statements
FAIL	github.com/project-alvarium/alvarium-sdk-go/pkg/config	0.005s
```

_Originally posted by @tsconn23 in https://github.com/project-alvarium/alvarium-sdk-go/pull/64#pullrequestreview-2136658582_

### PR DESCRIPTION
**Pull request by michaelehab**
Fix #65 
- Updated the static annotation used in TestSignAnnotation/valid_ed25519_signature to reflect the latest updates to the annotation schema (Like adding the tag and layer fields and fixing the kind field).
- Updated the test hash value corresponding to the static annotation in TestSignAnnotation/valid_ed25519_signature.
- Commented the invalid annotation type check, as it's not relevant after commenting out the annotation type checks.

### CODE REVIEW

File: pkg/config/sdk_test.go [hunk 1]
```diff
@@ -34,22 +33,22 @@ func TestSDKInfo_UnmarshalJSON(t *testing.T) {
...
-	}
-
-	cfg.Annotators = append(cfg.Annotators, "invalid")
-	b, _ = json.Marshal(cfg)
-
-	var x SdkInfo
-	err = json.Unmarshal(b, &x)
-	test.CheckError(err, true, "test sdk invalid annotation", t)
-}
+// func TestSDKInfo_AnnotationInvalid(t *testing.T) {
```
Comment (tsconn23) [inline pkg/config/sdk_test.go]: @michaelehab We should just remove this function. Its original purpose was to check the known list of annotator keys prior to introducing "custom annotators"

**Review by tsconn23 — CHANGES_REQUESTED** [review]

**Review by tsconn23 — APPROVED** [review]
